services:
  algatransito-api:
    build:
      context: . #diretório do arquivo Dockerfile
      dockerfile: Dockerfile #nome do arquivo Dockerfile
      # dockerfile: multistage.Dockerfile
    container_name: algatransito-api
    environment:
      - DB_HOST="mysql" #nome do service abaixo!! É usado no application.properties
    depends_on:
      - mysql
    ports:
      - 8080:8080
    networks:
      - algatransito-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=algatransito
      - MYSQL_USER=alga
      - MYSQL_PASSWORD=123456
    ports:
      - 3306:3306
    networks:
      - algatransito-network

networks:
  algatransito-network:
    driver: bridge
